--DELETE FROM llx_ho WHERE name='MONMODULE_IT_WORKS' AND entity='__ENTITY__';
--INSERT INTO llx_ho (name, value, type, note, visible, entity) VALUES ('MONMODULE_IT_WORKS','1','chaine','A constant vor my --module',1,'__ENTITY__');
